apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-0.mongodb-service.easyshop.svc.cluster.local:27017/easyshop"
  REDIS_URI: "redis://easyshop-redis.easyshop.svc.cluster.local:6379"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://34.221.61.212" 
  NEXTAUTH_URL: "http://34.221.61.212"  
  NEXTAUTH_SECRET: "PD3mtWFkDKTdAFSLsl3WVQLNfDNMzQKt+lFrHY888Wo="
  JWT_SECRET: "7bfe3aad7c610b07ab8145f1c2471d909ed918a559690f6bf628f4985cbdb5d9"
